name: Check

on:
  pull_request:
  push:
    branches:
      - main

env:
  POETRY_VERSION: 1.1.15
  PRE_COMMIT_VERSION: "2.21.0"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: .github/workflows/check.yaml

      - name: Install pre-commit
        run: pip install "pre-commit==$PRE_COMMIT_VERSION"

      - name: Set PY for pre-comit cache
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.PY }}-${{ env.PRE_COMMIT_VERSION }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files
